"use client"

import React from "react"
import Link from "next/link"
import { ArrowLeft } from "lucide-react"
import { Button } from "@/components/ui/button"

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-black text-white">
      <div className="max-w-4xl mx-auto px-4 py-12">
        <div className="mb-8">
          <Link href="/">
            <Button 
              variant="ghost" 
              className="text-gray-300 hover:text-white hover:bg-gray-800/50 mb-6"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Home
            </Button>
          </Link>
          <h1 className="text-4xl font-bold text-white mb-4">Privacy Policy</h1>
          <p className="text-gray-400">Effective Date: July 26, 2025</p>
        </div>

        <div className="prose prose-invert max-w-none">
          <p className="text-gray-300 mb-6">
            AI-Sidekick ("we", "us", or "our") respects your privacy. This Privacy Policy explains how we collect, use, and protect your information when you use our platform ("the Service"), which provides AI-powered business tools for service companies.
          </p>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">1. Information We Collect</h2>
            <p className="text-gray-300 mb-4">
              We collect the following types of information when you use the Service:
            </p>
            <ul className="list-disc list-inside text-gray-300 mb-4 space-y-2">
              <li><strong>Business Information:</strong> Such as company name, ZIP code, services offered, and team size during onboarding.</li>
              <li><strong>User Input:</strong> Messages, questions, and goals you enter into the chat interface.</li>
              <li><strong>Uploaded Content:</strong> Files, photos, or documents submitted for analysis.</li>
              <li><strong>Generated Content:</strong> Images or text outputs generated by the AI system in response to user input.</li>
              <li><strong>Usage Data:</strong> Anonymous usage patterns, including chat behavior and engagement data, used to improve the Service.</li>
            </ul>
            <p className="text-gray-300 mb-4">
              We do not collect sensitive personal information such as financial account details, Social Security numbers, or government ID data.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">2. How We Use Your Information</h2>
            <p className="text-gray-300 mb-4">
              We use your information to:
            </p>
            <ul className="list-disc list-inside text-gray-300 mb-4 space-y-2">
              <li>Deliver AI-powered responses, tools, and recommendations</li>
              <li>Generate images or suggestions based on prompts or uploads</li>
              <li>Analyze uploaded content for business insights</li>
              <li>Improve the quality, accuracy, and functionality of the Service</li>
              <li>Monitor usage patterns and detect abuse</li>
              <li>Enforce safety through automated content moderation</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">3. Sharing and Disclosure</h2>
            <p className="text-gray-300 mb-4">
              We do not sell or rent your data. We may share limited information with trusted third-party service providers as needed to:
            </p>
            <ul className="list-disc list-inside text-gray-300 mb-4 space-y-2">
              <li>Process requests (e.g., analyze files, generate images)</li>
              <li>Store and deliver your data securely</li>
              <li>Provide technical or user support</li>
            </ul>
            <p className="text-gray-300 mb-4">
              All third parties are bound by confidentiality and data protection agreements.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">4. Content Moderation</h2>
            <p className="text-gray-300 mb-4">
              We use automated moderation tools to help detect and block content that may be:
            </p>
            <ul className="list-disc list-inside text-gray-300 mb-4 space-y-2">
              <li>Abusive, hateful, threatening, or discriminatory</li>
              <li>Sexually explicit or otherwise inappropriate</li>
              <li>Misleading or deceptive</li>
              <li>In violation of intellectual property or applicable law</li>
            </ul>
            <p className="text-gray-300 mb-4">
              These systems help keep the Service safe for all users.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">5. Data Retention</h2>
            <p className="text-gray-300 mb-4">
              We retain data only as long as needed to:
            </p>
            <ul className="list-disc list-inside text-gray-300 mb-4 space-y-2">
              <li>Provide services</li>
              <li>Improve functionality</li>
              <li>Meet legal or operational obligations</li>
            </ul>
            <p className="text-gray-300 mb-4">
              You may request deletion of your account or associated files at any time.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">6. Security</h2>
            <p className="text-gray-300 mb-4">
              We use appropriate technical and organizational safeguards to protect your data against unauthorized access, misuse, or alteration.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">7. Your Rights</h2>
            <p className="text-gray-300 mb-4">
              You have the right to:
            </p>
            <ul className="list-disc list-inside text-gray-300 mb-4 space-y-2">
              <li>Access your profile information</li>
              <li>Request deletion or correction of your business data</li>
              <li>Withdraw consent for data processing</li>
              <li>Request a copy of your stored data (where applicable)</li>
            </ul>
            <p className="text-gray-300 mb-4">
              To make a request, contact us at legal@ai-sidekick.io.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">8. Children's Privacy</h2>
            <p className="text-gray-300 mb-4">
              The Service is not intended for use by children under 13. We do not knowingly collect data from minors.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">9. Policy Updates</h2>
            <p className="text-gray-300 mb-4">
              We may update this Privacy Policy periodically. If material changes occur, we will notify you through the platform or by email.
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}