"use client"

import React from "react"
import Link from "next/link"
import { ArrowLeft } from "lucide-react"
import { Button } from "@/components/ui/button"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black text-white">
      <div className="max-w-4xl mx-auto px-4 py-12">
        <div className="mb-8">
          <Link href="/">
            <Button 
              variant="ghost" 
              className="text-gray-300 hover:text-white hover:bg-gray-800/50 mb-6"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Back to Home
            </Button>
          </Link>
          <h1 className="text-4xl font-bold text-white mb-4">Terms of Use</h1>
          <p className="text-gray-400">Effective Date: January 11, 2025</p>
          <p className="text-gray-400">Last Updated: July 10, 2025</p>
        </div>

        <div className="prose prose-invert max-w-none">
          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">1. Overview</h2>
            <p className="text-gray-300 mb-4">
              AI Sidekick is a limited early-access software tool that provides AI-generated business assistance for trades-based businesses. By using the service, you agree to these terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">2. Trial Use Only</h2>
            <p className="text-gray-300 mb-4">
              The current version of AI Sidekick is available as a free trial for 7 days. After that, continued access may require a paid subscription.
            </p>
            <p className="text-gray-300 mb-4">
              We may modify or suspend features at any time during the trial.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">3. User Responsibilities</h2>
            <p className="text-gray-300 mb-4">
              You agree to:
            </p>
            <ul className="list-disc list-inside text-gray-300 mb-4 space-y-2">
              <li>Use AI Sidekick only for lawful business purposes</li>
              <li>Provide accurate business info when creating your profile</li>
              <li>Not use the AI for harmful, misleading, or illegal purposes</li>
              <li>Not attempt to reverse engineer or misuse the service</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">4. AI Disclaimer</h2>
            <p className="text-gray-300 mb-4">
              AI Sidekick uses artificial intelligence to generate suggestions. While we aim for helpful, relevant responses, we do not guarantee accuracy, legal compliance, or business results. Use your own judgment when applying any advice provided.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">5. Data Use and Retention</h2>
            <p className="text-gray-300 mb-4">
              During your trial, we may store your business profile, chat messages, and feedback for the purpose of improving the experience. This data is not sold or shared externally and is deleted automatically if your account is inactive for more than 30 days.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">6. Intellectual Property</h2>
            <p className="text-gray-300 mb-4">
              All content generated by the AI is yours to use for your business. The platform, models, and underlying code remain the intellectual property of AI Sidekick and its partners.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">7. Termination</h2>
            <p className="text-gray-300 mb-4">
              You may stop using the product at any time. We may suspend or terminate access at our discretion if terms are violated or for misuse of the system.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">8. Limitation of Liability</h2>
            <p className="text-gray-300 mb-4">
              We are not liable for any damages, business losses, or decisions made based on AI-generated content. The service is offered "as is" without warranties of any kind.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">9. Governing Law</h2>
            <p className="text-gray-300 mb-4">
              These terms are governed by the laws of the State of Texas. Any disputes will be handled in state or federal courts located in Texas.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-emerald-400 mb-4">10. Contact</h2>
            <p className="text-gray-300 mb-4">
              Have questions about the terms?
            </p>
            <p className="text-gray-300">
              Email: hello@aisidekick.com
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}